# Chapter 16 - Project: Organizing sales data by channel

In [2]:
# Basic Libraries
import pandas as pd

In [3]:
# Read a Excel file, a specific sheet
jan_sales_df = pd.read_excel('data/Q1Sales.xlsx', sheet_name='January')

jan_sales_df.head(3)

,InvoiceNo,Channel,Product Name,ProductID,Account,AccountNo,Date,Deadline,Currency,Unit Price,Quantity,Total
0,1532,Shoppe.com,Cannon Water Bomb Balloons 100 Pack,T&G/CAN-97509,Sales,5004,2020-01-01,11/23/19,USD,20.11,14,281.54
1,1533,Walcart,LEGO Ninja Turtles Stealth Shell in Pursuit 79102,T&G/LEG-37777,Sales,5004,2020-01-01,06/15/20,USD,6.70,1,6.70
2,1534,Bullseye,NaN,T&G/PET-14209,Sales,5004,2020-01-01,05/07/20,USD,11.67,5,58.35

In [4]:
feb_sales_df = pd.read_excel('data/Q1Sales.xlsx', sheet_name='February')
mar_sales_df = pd.read_excel('data/Q1Sales.xlsx', sheet_name='March')

In [5]:
mar_sales_df.tail(3)

,InvoiceNo,Channel,Product Name,ProductID,Account,AccountNo,Date,Deadline,Currency,Unit Price,Quantity,Total
9751,39219,Shoppe.com,MONO GS1 GS1-BTY-BLK-L Betty Long Guitar Strap...,MI/MON-86723,Sales,5004,2020-03-31,04/11/20,USD,3.33,1,3.33
9752,39238,Shoppe.com,NaN,T&G/MAG-68412,Sales,5004,2020-03-31,3-20-20,USD,34.76,10,347.60
9753,39239,Understock.com,3 Collapsible Bowl Set 32oz | 16oz | 4oz,K&D/3 C-07383,Sales,5004,2020-03-31,April 02 2020,USD,6.39,15,95.85

In [6]:
sales_df = pd.concat([jan_sales_df, feb_sales_df, mar_sales_df], ignore_index=True)

sales_df

,InvoiceNo,Channel,Product Name,ProductID,Account,AccountNo,Date,Deadline,Currency,Unit Price,Quantity,Total
0,1532,Shoppe.com,Cannon Water Bomb Balloons 100 Pack,T&G/CAN-97509,Sales,5004,2020-01-01,11/23/19,USD,20.11,14,281.54
1,1533,Walcart,LEGO Ninja Turtles Stealth Shell in Pursuit 79102,T&G/LEG-37777,Sales,5004,2020-01-01,06/15/20,USD,6.70,1,6.70
2,1534,Bullseye,NaN,T&G/PET-14209,Sales,5004,2020-01-01,05/07/20,USD,11.67,5,58.35
3,1535,Bullseye,Transformers Age of Extinction Generations Del...,T&G/TRA-20170,Sales,5004,2020-01-01,12/22/19,USD,13.46,6,80.76
4,1535,Bullseye,Transformers Age of Extinction Generations Del...,T&G/TRA-20170,Sales,5004,2020-01-01,12/22/19,USD,13.46,6,80.76
...,...,...,...,...,...,...,...,...,...,...,...,...
37703,39235,iBay.com,"Nature's Bounty Garlic, 2000mg, Odor-Free, 120...",H&PC/NAT-15470,Sales,5004,2020-03-31,Thu Sep 17 00:00:00 2020,USD,5.55,2,11.10
37704,39216,Shoppe.com,Funko Wonder Woman POP Heroes,T&G/FUN-03366,Sales,5004,2020-03-31,5-08-20,USD,28.56,1,28.56
37705,39219,Shoppe.com,MONO GS1 GS1-BTY-BLK-L Betty Long Guitar Strap...,MI/MON-86723,Sales,5004,2020-03-31,04/11/20,USD,3.33,1,3.33
37706,39238,Shoppe.com,NaN,T&G/MAG-68412,Sales,5004,2020-03-31,3-20-20,USD,34.76,10,347.60
37707,39239,Understock.com,3 Collapsible Bowl Set 32oz | 16oz | 4oz,K&D/3 C-07383,Sales,5004,2020-03-31,April 02 2020,USD,6.39,15,95.85

In [7]:
# Direct form:

sales_df = pd.concat([  # Concatenate the data from multiple Excel sheets into a single DataFrame
        pd.read_excel('data/Q1Sales.xlsx', sheet_name='January'),   # Read data from the 'January' sheet
        pd.read_excel('data/Q1Sales.xlsx', sheet_name='February'),  # Read data from the 'February' sheet
        pd.read_excel('data/Q1Sales.xlsx', sheet_name='March')      # Read data from the 'March' sheet
    ], 
    ignore_index=True)  # Ignore the original row indices and reset the index in the concatenated DataFrame

sales_df

,InvoiceNo,Channel,Product Name,ProductID,Account,AccountNo,Date,Deadline,Currency,Unit Price,Quantity,Total
0,1532,Shoppe.com,Cannon Water Bomb Balloons 100 Pack,T&G/CAN-97509,Sales,5004,2020-01-01,11/23/19,USD,20.11,14,281.54
1,1533,Walcart,LEGO Ninja Turtles Stealth Shell in Pursuit 79102,T&G/LEG-37777,Sales,5004,2020-01-01,06/15/20,USD,6.70,1,6.70
2,1534,Bullseye,NaN,T&G/PET-14209,Sales,5004,2020-01-01,05/07/20,USD,11.67,5,58.35
3,1535,Bullseye,Transformers Age of Extinction Generations Del...,T&G/TRA-20170,Sales,5004,2020-01-01,12/22/19,USD,13.46,6,80.76
4,1535,Bullseye,Transformers Age of Extinction Generations Del...,T&G/TRA-20170,Sales,5004,2020-01-01,12/22/19,USD,13.46,6,80.76
...,...,...,...,...,...,...,...,...,...,...,...,...
37703,39235,iBay.com,"Nature's Bounty Garlic, 2000mg, Odor-Free, 120...",H&PC/NAT-15470,Sales,5004,2020-03-31,Thu Sep 17 00:00:00 2020,USD,5.55,2,11.10
37704,39216,Shoppe.com,Funko Wonder Woman POP Heroes,T&G/FUN-03366,Sales,5004,2020-03-31,5-08-20,USD,28.56,1,28.56
37705,39219,Shoppe.com,MONO GS1 GS1-BTY-BLK-L Betty Long Guitar Strap...,MI/MON-86723,Sales,5004,2020-03-31,04/11/20,USD,3.33,1,3.33
37706,39238,Shoppe.com,NaN,T&G/MAG-68412,Sales,5004,2020-03-31,3-20-20,USD,34.76,10,347.60
37707,39239,Understock.com,3 Collapsible Bowl Set 32oz | 16oz | 4oz,K&D/3 C-07383,Sales,5004,2020-03-31,April 02 2020,USD,6.39,15,95.85

In [8]:
channel = 'Understock.com'
channel_df = sales_df[sales_df['Channel'] == channel]
channel_df = channel_df.sort_values(['Total', 'Quantity'], ascending=False)

In [9]:
# Define the channel name to filter data from the 'sales_df' DataFrame
channel = 'Understock.com'  

# Filter the 'sales_df' DataFrame to include only rows where the 'Channel' column is equal to 'Understock.com'
channel_df = sales_df[sales_df['Channel'] == channel]  

# Sort the filtered data first by 'Total' in descending order, and then by 'Quantity' in descending order
channel_df = channel_df.sort_values(['Total', 'Quantity'], ascending=False)  

channel_df

,InvoiceNo,Channel,Product Name,ProductID,Account,AccountNo,Date,Deadline,Currency,Unit Price,Quantity,Total
23620,25152,Understock.com,Large Display Digital Thermometer Lumiscope,H&PC/LAR-98606,Sales,5004,2020-02-21,Sun Dec 22 00:00:00 2019,USD,64.32,54,3473.28
36621,38153,Understock.com,Large Display Digital Thermometer Lumiscope,H&PC/LAR-98606,Sales,5004,2020-03-26,Sun Apr 19 00:00:00 2020,USD,64.32,54,3473.28
4747,6279,Understock.com,AC Adapter/battery charger for GateWay Liteon ...,E/AC-44106,Sales,5004,2020-01-10,2020/02/05,USD,14.88,226,3362.88
4757,6162,Understock.com,AC Adapter/battery charger for GateWay Liteon ...,E/AC-44106,Sales,5004,2020-01-10,2020/02/05,USD,14.88,226,3362.88
4969,6397,Understock.com,AC Adapter/battery charger for GateWay Liteon ...,E/AC-44106,Sales,5004,2020-01-10,2020/02/05,USD,14.88,226,3362.88
...,...,...,...,...,...,...,...,...,...,...,...,...
15679,17002,Understock.com,"Urban Rebounding Workout DVD, Compilation 1",M&T/URB-83617,Sales,5004,2020-02-04,July 02 2020,USD,1.69,1,1.69
12877,14409,Understock.com,Magic: the Gathering - Hydra Broodmaster (126/...,T&G/MAG-22549,Sales,5004,2020-01-29,4-13-20,USD,0.06,17,1.02
15855,17387,Understock.com,Magic: the Gathering - Hydra Broodmaster (126/...,T&G/MAG-22549,Sales,5004,2020-02-05,1-14-20,USD,0.06,11,0.66
24012,25544,Understock.com,Magic: the Gathering - Hydra Broodmaster (126/...,T&G/MAG-22549,Sales,5004,2020-02-22,6-19-20,USD,0.06,11,0.66
24022,25466,Understock.com,Magic: the Gathering - Hydra Broodmaster (126/...,T&G/MAG-22549,Sales,5004,2020-02-22,6-19-20,USD,0.06,11,0.66

We can write `channel_df` to a new Excel file using:

In [11]:
channel_df.to_excel('data/Q1ChannelSales.xlsx', sheet_name='Understock.com', index=False)

In [12]:
channels = ['Bullseye', 'iBay.com', 'Shoppe.com', 'Understock.com', 'Walcart']

for channel in channels:
    print(channel)

Bullseye
iBay.com
Shoppe.com
Understock.com
Walcart

In [13]:
channels = ['Bullseye', 'iBay.com', 'Shoppe.com', 'Understock.com', 'Walcart']

for channel in channels:
    channel_df = sales_df[sales_df['Channel'] == channel]
    channel_df = channel_df.sort_values(['Total', 'Quantity'], ascending=False)

channel_df

,InvoiceNo,Channel,Product Name,ProductID,Account,AccountNo,Date,Deadline,Currency,Unit Price,Quantity,Total
2461,3993,Walcart,Large Display Digital Thermometer Lumiscope,H&PC/LAR-98606,Sales,5004,2020-01-06,Mon Jun 22 00:00:00 2020,USD,64.47,23,1482.81
8332,9864,Walcart,AC Adapter/battery charger for GateWay Liteon ...,E/AC-44106,Sales,5004,2020-01-18,2019/12/02,USD,14.49,100,1449.00
15293,16825,Walcart,AC Adapter/battery charger for GateWay Liteon ...,E/AC-44106,Sales,5004,2020-02-04,2019/11/29,USD,14.49,100,1449.00
15509,16895,Walcart,AC Adapter/battery charger for GateWay Liteon ...,E/AC-44106,Sales,5004,2020-02-04,2019/11/29,USD,14.49,100,1449.00
23888,25420,Walcart,AC Adapter/battery charger for GateWay Liteon ...,E/AC-44106,Sales,5004,2020-02-21,2020/02/14,USD,14.49,100,1449.00
...,...,...,...,...,...,...,...,...,...,...,...,...
936,2332,Walcart,Vibrating Slim Jelly Dong with Suction Cup 7.5...,H&PC/VIB-56252,Sales,5004,2020-01-02,Thu Jan 2 00:00:00 2020,USD,2.10,1,2.10
11222,12754,Walcart,Vibrating Slim Jelly Dong with Suction Cup 7.5...,H&PC/VIB-56252,Sales,5004,2020-01-25,Wed Dec 18 00:00:00 2019,USD,2.10,1,2.10
14186,15718,Walcart,"Blackberry Q10 White 16GB Factory Unlocked, In...",CP&A/BLA-26278,Sales,5004,2020-02-01,Tue Mar 10 00:00:00 2020,USD,1.87,1,1.87
14311,15712,Walcart,"Blackberry Q10 White 16GB Factory Unlocked, In...",CP&A/BLA-26278,Sales,5004,2020-02-01,Tue Mar 10 00:00:00 2020,USD,1.87,1,1.87
33627,35159,Walcart,"Red Dragon VT 3-30 C 500,000 BTU Heavy Duty Pr...",PL&G/RED-46561,Sales,5004,2020-03-15,07/19/20,USD,0.19,6,1.14

Why 'Walcart' sales? Because the for loop goes through all values
in the channels list and keeps assigning a different DataFrame to
channel_df. The last value in the channels list is 'Walcart', so at
the last iteration of the loop, channel_df gets assigned only those
rows in sales_df where values in the 'Channel' column are equal
to 'Walcart'.

In [15]:
# Define a list of channel names to iterate over
channels = ['Bullseye', 'iBay.com', 'Shoppe.com', 'Understock.com', 'Walcart']  

# Create an ExcelWriter object to write data to a new Excel file 'Q1ChannelSales.xlsx'
output_file = pd.ExcelWriter('data/Q1ChannelSales.xlsx')

for channel in channels:                                                         # Loop through each channel in the 'channels' list
    channel_df = sales_df[sales_df['Channel'] == channel]                        # Filter the 'sales_df' with only rows for the current channel
    channel_df = channel_df.sort_values(['Total', 'Quantity'], ascending=False)  # Sort the filtered data by 'Total' and 'Quantity' in descending order
    channel_df.to_excel(output_file, sheet_name=channel, index=False)            # Write the sorted data to a new sheet in the Excel file

output_file.close()                                                              # Save the Excel file after all sheets have been written

Another way:

In [17]:
# Define a list of channel names to iterate over
channels = ['Bullseye', 'iBay.com', 'Shoppe.com', 'Understock.com', 'Walcart']  

with pd.ExcelWriter('data/Q1ChannelSales2.xlsx') as output_file:
    for channel in channels:
        channel_df = sales_df[sales_df['Channel'] == channel]
        channel_df = channel_df.sort_values(['Total', 'Quantity'], ascending=False)
        channel_df.to_excel(output_file, sheet_name=channel, index=False)

Concatenating all:

In [19]:
sales_df = pd.concat([
        pd.read_excel('data/Q1Sales.xlsx', sheet_name='January'), 
        pd.read_excel('data/Q1Sales.xlsx', sheet_name='February'), 
        pd.read_excel('data/Q1Sales.xlsx', sheet_name='March')
    ], ignore_index=True)

channels = ['Bullseye', 'iBay.com', 'Shoppe.com', 'Understock.com', 'Walcart']

with pd.ExcelWriter('data/Q1ChannelSales4.xlsx') as output_file:
    for channel in channels:
        channel_df = sales_df[sales_df['Channel'] == channel]
        channel_df = channel_df.sort_values(['Total', 'Quantity'], ascending=False)
        channel_df.to_excel(output_file, sheet_name=channel, index=False)